### ISSUE TITLE
Publishing!

### ISSUE THREAD

**Issue by trevor-scheer** [apollo-server-integrations/apollo-server-integration-azure-functions#19]
Hey @aaronpowell, caught your comment over here: https://github.com/apollographql/apollo-server/issues/6032#issuecomment-1373199073.

Sorry for the delay.

I sent you an invite to the NPM org and added you to the `azure-functions` team. You should be able to generate an automation token and add it to the repository secrets here: https://github.com/apollo-server-integrations/apollo-server-integration-azure-functions/settings/secrets/actions (under `NPM_TOKEN`). This will allow changesets to start publishing to NPM.

Bug me here or send me an email if you have any questions, and let me know when you publish!

**Comment by aaronpowell** [comment]
Thanks, I've joined and will see about publishing soon

**Comment by aaronpowell** [comment]
@trevor-scheer - I just went to setup publishing but I'm not an admin of the repo, so I can't add the secret to GitHub Actions. Can you grant that permission to me?

**Comment by trevor-scheer** [comment]
@aaronpowell done!
