### ISSUE TITLE
Invalid handling of JSON body data

### ISSUE THREAD

**Issue by Jon-Salmon** [apollo-server-integrations/apollo-server-integration-azure-functions#21]
https://github.com/apollo-server-integrations/apollo-server-integration-azure-functions/blob/d567e718247e688b7818acc6966a94099b76e68f/src/index.ts#L92-L93

When parsing the body of the request with a content-type of `application/json`, the body is expected as a string and converted. However, it seems that the body parameter passed from @azure/functions is actually already a parsed object with the following type definition:
```
    /**
     * The HTTP request body.
     * If the media type is 'application/octet-stream' or 'multipart/*', this will be a Buffer
     * If the value is a JSON parse-able string, this will be the parsed object
     * Otherwise, this will be a string
     */
    body?: any;
```

**Comment by aaronpowell** [comment]
My bad - fixing with #23.
