### ISSUE TITLE
Issue with BaseContext type (possibly user error)

### ISSUE THREAD

**Issue by drake-nathan** [apollo-server-integrations/apollo-server-integration-azure-functions#26]
First, thanks for making this! I got it running but had a slight issue with the generic type passed to `ApolloServer`. This is my first time setting up Apollo.

This is what my `apolloServer` shows as the type: `ApolloServer<GraphQLResolveInfo>`

But I have to do this to get it working: 
```
export default startServerAndCreateHandler(
  apolloServer as unknown as ApolloServer<BaseContext>,
);
```
Perhaps I'm missing something? Here's my Apollo setup, in case that helps:
```
const typeDefs = `#graphql
  scalar Date

  type Nft {
    id: ID!
    createdAt: Date!
    updatedAt: Date!
    name: String!
  }

  type Query {
    nft(id: ID!): Nft
    allNfts: [Nft]
  }
`;

const resolvers: Resolvers = {
  Date: DateResolver,
  Query: {
    allNfts: async () => {
      const nfts = await prismaClient.nft.findMany();
      return nfts;
    },
    nft: async (_, { id }) => {
      const nft = await prismaClient.nft.findUnique({ where: { id } });
      return nft;
    },
  },
};

export const apolloServer = new ApolloServer({ typeDefs, resolvers });
```

**Comment by aaronpowell** [comment]
You'd be better off asking the question on https://community.apollographql.com/ than here - this repo is for issues specifically related to the Azure Functions integration.
