### ISSUE TITLE
Content-Type too strict

### ISSUE THREAD

**Issue by kmcgill88** [apollo-server-integrations/apollo-server-integration-azure-functions#27]
I ran into an issue where some clients are sending `Content-Type: application/json; charset-utf8` and tracked the issue back to [this integration](https://github.com/apollo-server-integrations/apollo-server-integration-azure-functions/blob/main/src/index.ts#L92). If the content type doesn't match exactly empty string is return and the downstream apollo server naturally explodes.

Apollo uses a [startsWith](https://github.com/apollographql/federation/blob/%40apollo/gateway%402.3.2/gateway-js/src/datasources/RemoteGraphQLDataSource.ts#L287) to check the content type and ignores charset.

I think this needs to support
`application/graphql-response+json;charset=utf-8` (apparently in draft spec)
`application/json; charset-utf8`
`application/json`

Without the content-type being exactly `application/json` the function app responds with a 400 and `"POST body missing, invalid Content-Type, or JSON object has no keys."` since the body is actually an empty string.

**Comment by kmcgill88** [comment]
I'm not positive how to test this but I think the [implementation could look like this](https://github.com/kmcgill88/apollo-server-integration-azure-functions/blob/refactor-content-type-parsing/src/index.ts#L87)

**Comment by shellicar** [comment]
This seems to be an issue if sending with application/graphql content-type.
Was stumping me for a while.

Was getting this error
```
POST body missing, invalid Content-Type, or JSON object has no keys.
```
Seems to be due to the code linked is returning an empty string instead of the contents of the body.

**Comment by kmcgill88** [comment]
@shellicar  the PR I opened (https://github.com/apollo-server-integrations/apollo-server-integration-azure-functions/pull/28) doesn't cover `application/graphql`. According to [graphql org website](https://graphql.org/learn/serving-over-http/#post-request) it looks like it should!

**Comment by shellicar** [comment]
I believe this was closed in error.
I get the following error on every request in 0.1.1
```
"message": "POST body missing, invalid Content-Type, or JSON object has no keys."
```

I believe this is due to the removal of returning the body when typeof body is not equal to 'string', as it may be an object.

Previous effective code.
```
if (typeof body === 'string') {
  return JSON.parse(body);
}
return body;
```
New effective code
```
if (typeof body === 'string')
  return JSON.parse(body);
}
return null;
```

**Comment by kmcgill88** [comment]
@shellicar this issue was closed and resolved the issue's original intent. You mentioned the header `application/graphql` which wasn't covered as I originally stated.

The [latest code](https://github.com/apollo-server-integrations/apollo-server-integration-azure-functions/blob/main/src/index.ts#L87), particularly `const isValidContentType = contentType?.startsWith('application/json');`  can easily be refactored to `const isValidContentType = contentType?.startsWith('application/json') || contentType?.startsWith('application/graphql');` and resolve your issue.

I believe returning null is the correct thing to do when method is *not* a POST since a GET is a legal graph request but of course does not have a body. I believe [this](https://github.com/apollo-server-integrations/apollo-server-integration-azure-functions/blob/main/src/index.ts#L82) covers the GET.

**Comment by shellicar** [comment]
If I browse to the in-built Apollo Server browser and try to use the API, I observe the behaviour I mentioned.
This has nothing to do with the content type for graphql, but the string parsing for application/json.

To be clear, this has nothing to do with any request I'm sending, but the request the in-built browser is sending.
