### ISSUE TITLE
Azure Function can reuse the handler and the start function is called multiple times

### ISSUE THREAD

**Issue by royvou** [apollo-server-integrations/apollo-server-integration-azure-functions#29]
First of all nice work on the package, we are currently migrating to AS4 with Azure Functions 4 and this package is a great help.

We only noticed that when querying from Apollo Client we got the message
 `You should only call 'start()' or 'startInBackgroundHandlingStartupErrorsByLoggingAndFailingAllRequests()' once on your ApolloServer.`
as a single handler could be reused across multiple requests.

We should add a check to prevent duplicate start commandos / let users provide an started client to the handler (And call it `createHandler`)

**Comment by royvou** [comment]
I will add some reproduction sample... 

When using a simple GraphQL client (E.g [Altair](https://github.com/altair-graphql/altair) we didn't observe any issues, but when we call it from our client app (NextJS/Apollo Client) this was happening 100% of the time...

**Comment by royvou** [comment]
Issue can be closed, the server was being started every request :/

**Comment by aaronpowell** [comment]
> Issue can be closed, the server was being started every request :/

In the case of Azure Functions, this is expected, as the serverless host isn't persisted between executions.
