### ISSUE TITLE
Support for CORS

### ISSUE THREAD

**Issue by shashankkr** [apollo-server-integrations/apollo-server-integration-azure-functions#45]
Hi,
How can I add CORS support to allow any origin?

https://www.apollographql.com/docs/apollo-server/security/cors/

**Comment by aaronpowell** [comment]
This is something that you manage on Azure, not within the codebase. See [this docs link](https://learn.microsoft.com/azure/azure-functions/functions-how-to-use-azure-function-app-settings?tabs=portal#cors) for more guidance
